---
name: Linting

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker
        run: |
          make build

      - name: Run linting
        run: |
          make lint-root

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and Run mypy
        run: |
          pip install mypy
          mypy --install-types --non-interactive --ignore-missing-imports eo3/
