---
name: Tests

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build Docker
        run: |
          make build

      - name: Run tests
        run: |
          make test-root

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          use_oidc: true
          fail_ci_if_error: false
